export const INDIAN_LOCATIONS = [
  { city: "Adilabad", state: "Telangana" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Agartala", state: "Tripura" },
  { city: "Agar Malwa", state: "Madhya Pradesh" },
  { city: "Agatti", state: "Lakshadweep (UT)" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Alappuzha", state: "Kerala" },
  { city: "Aliganj", state: "Uttar Pradesh" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Alirajpur", state: "Madhya Pradesh" },
  { city: "Allahabad", state: "Uttar Pradesh" },
  { city: "Almora", state: "Uttarakhand" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Amala", state: "Haryana" },
  { city: "Ambala", state: "Haryana" },
  { city: "Ambedkar Nagar", state: "Uttar Pradesh" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Amreli", state: "Gujarat" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Anand", state: "Gujarat" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Anantnag", state: "Jammu and Kashmir" },
  { city: "Angul", state: "Odisha" },
  { city: "Anjaw", state: "Arunachal Pradesh" },
  { city: "Anuppur", state: "Madhya Pradesh" },
  { city: "Araria", state: "Bihar" },
  { city: "Aravalli", state: "Gujarat" },
  { city: "Areraj", state: "Bihar" },
  { city: "Ariyalur", state: "Tamil Nadu" },
  { city: "Arrah", state: "Bihar" },
  { city: "Arwal", state: "Bihar" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Ashoknagar", state: "Madhya Pradesh" },
  { city: "Asthawan", state: "Bihar" },
  { city: "Auraiya", state: "Uttar Pradesh" },
  { city: "Aurangabad", state: "Bihar" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Azamgarh", state: "Uttar Pradesh" },
  { city: "Badaun", state: "Uttar Pradesh" },
  { city: "Bagaha", state: "Bihar" },
  { city: "Bagalkot", state: "Karnataka" },
  { city: "Bageshwar", state: "Uttarakhand" },
  { city: "Baghpat", state: "Uttar Pradesh" },
  { city: "Bahadurganj", state: "Bihar" },
  { city: "Bahraich", state: "Uttar Pradesh" },
  { city: "Baisi", state: "Bihar" },
  { city: "Bakhtiyarpur", state: "Bihar" },
  { city: "Baksa", state: "Assam" },
  { city: "Balaghat", state: "Madhya Pradesh" },
  { city: "Balangir", state: "Odisha" },
  { city: "Balasore", state: "Odisha" },
  { city: "Ballari (Bellary)", state: "Karnataka" },
  { city: "Ballia", state: "Uttar Pradesh" },
  { city: "Balod", state: "Chhattisgarh" },
  { city: "Baloda Bazar", state: "Chhattisgarh" },
  { city: "Balrampur", state: "Chhattisgarh" },
  { city: "Balrampur", state: "Uttar Pradesh" },
  { city: "Banaskantha (Palanpur)", state: "Gujarat" },
  { city: "Banda", state: "Uttar Pradesh" },
  { city: "Bandipore", state: "Jammu and Kashmir" },
  { city: "Bangalore Rural", state: "Karnataka" },
  { city: "Bangalore Urban", state: "Karnataka" },
  { city: "Banka", state: "Bihar" },
  { city: "Banswara", state: "Rajasthan" },
  { city: "Barabanki", state: "Uttar Pradesh" },
  { city: "Baramulla", state: "Jammu and Kashmir" },
  { city: "Baran", state: "Rajasthan" },
  { city: "Bardhaman", state: "West Bengal" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Bargarh", state: "Odisha" },
  { city: "Barh", state: "Bihar" },
  { city: "Barkot", state: "Uttarakhand" },
  { city: "Barmer", state: "Rajasthan" },
  { city: "Barnala", state: "Punjab" },
  { city: "Barpeta", state: "Assam" },
  { city: "Barun", state: "Bihar" },
  { city: "Barwani", state: "Madhya Pradesh" },
  { city: "Bastar", state: "Chhattisgarh" },
  { city: "Basti", state: "Uttar Pradesh" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Beed", state: "Maharashtra" },
  { city: "Begusarai", state: "Bihar" },
  { city: "Belagavi (Belgaum)", state: "Karnataka" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Belsand", state: "Bihar" },
  { city: "Bemetara", state: "Chhattisgarh" },
  { city: "Benipatti", state: "Bihar" },
  { city: "Betul", state: "Madhya Pradesh" },
  { city: "Bettiah", state: "Bihar" },
  { city: "Bhadohi", state: "Uttar Pradesh" },
  { city: "Bhadrak", state: "Odisha" },
  { city: "Bhalwal", state: "Jammu and Kashmir" },
  { city: "Bhandara", state: "Maharashtra" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Bharuch", state: "Gujarat" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Bhid", state: "Madhya Pradesh" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Bhimavaram", state: "Andhra Pradesh" },
  { city: "Bhind", state: "Madhya Pradesh" },
  { city: "Bhiwani", state: "Haryana" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Bhuj", state: "Gujarat" },
  { city: "Bhusawal", state: "Maharashtra" },
  { city: "Bidar", state: "Karnataka" },
  { city: "Bihar Sharif", state: "Bihar" },
  { city: "Bihiya", state: "Bihar" },
  { city: "Bijapur", state: "Chhattisgarh" },
  { city: "Bijapur", state: "Karnataka" },
  { city: "Bijnor", state: "Uttar Pradesh" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Bikramganj", state: "Bihar" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Bilaspur", state: "Himachal Pradesh" },
  { city: "Biraul", state: "Bihar" },
  { city: "Birbhum", state: "West Bengal" },
  { city: "Birpur", state: "Bihar" },
  { city: "Bisfi", state: "Bihar" },
  { city: "Bishnupur", state: "Manipur" },
  { city: "Biswanath", state: "Assam" },
  { city: "Bodh Gaya", state: "Bihar" },
  { city: "Bokaro", state: "Jharkhand" },
  { city: "Bongaigaon", state: "Assam" },
  { city: "Botad", state: "Gujarat" },
  { city: "Boudh", state: "Odisha" },
  { city: "Budgam", state: "Jammu and Kashmir" },
  { city: "Bulandshahr", state: "Uttar Pradesh" },
  { city: "Buldhana", state: "Maharashtra" },
  { city: "Bundi", state: "Rajasthan" },
  { city: "Burhanpur", state: "Madhya Pradesh" },
  { city: "Buxar", state: "Bihar" },
  { city: "Cachar", state: "Assam" },
  { city: "Central Delhi", state: "Delhi (NCT)" },
  { city: "Chaiasa", state: "Jharkhand" },
  { city: "Chail", state: "Uttar Pradesh" },
  { city: "Chainpur", state: "Bihar" },
  { city: "Chakai", state: "Bihar" },
  { city: "Chakia", state: "Bihar" },
  { city: "Chamba", state: "Himachal Pradesh" },
  { city: "Chamoli", state: "Uttarakhand" },
  { city: "Champawat", state: "Uttarakhand" },
  { city: "Champhai", state: "Mizoram" },
  { city: "Chandauli", state: "Uttar Pradesh" },
  { city: "Chandel", state: "Manipur" },
  { city: "Chandigarh", state: "Chandigarh (UT)" },
  { city: "Chandrapur", state: "Maharashtra" },
  { city: "Changlang", state: "Arunachal Pradesh" },
  { city: "Charkhi Dadri", state: "Haryana" },
  { city: "Chatra", state: "Jharkhand" },
  { city: "Chenari", state: "Bihar" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Chhapra", state: "Bihar" },
  { city: "Chhatarpur", state: "Madhya Pradesh" },
  { city: "Chhindwara", state: "Madhya Pradesh" },
  { city: "Chhota Udepur", state: "Gujarat" },
  { city: "Chikballapur", state: "Karnataka" },
  { city: "Chikkamagaluru (Chikmagalur)", state: "Karnataka" },
  { city: "Chirang", state: "Assam" },
  { city: "Chitradurga", state: "Karnataka" },
  { city: "Chitrakoot", state: "Uttar Pradesh" },
  { city: "Chittoor", state: "Andhra Pradesh" },
  { city: "Chittorgarh", state: "Rajasthan" },
  { city: "Churachandpur", state: "Manipur" },
  { city: "Churu", state: "Rajasthan" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Cooch Behar", state: "West Bengal" },
  { city: "Cuddalore", state: "Tamil Nadu" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Dadra & Nagar Haveli", state: "Dadra and Nagar Haveli (UT)" },
  { city: "Dahod", state: "Gujarat" },
  { city: "Dakshina Kannada", state: "Karnataka" },
  { city: "Dalsinghsarai", state: "Bihar" },
  { city: "Daman", state: "Daman and Diu (UT)" },
  { city: "Damoh", state: "Madhya Pradesh" },
  { city: "Danapur", state: "Bihar" },
  { city: "Dangs (Ahwa)", state: "Gujarat" },
  { city: "Dantewada (South Bastar)", state: "Chhattisgarh" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Darjeeling", state: "West Bengal" },
  { city: "Darrang", state: "Assam" },
  { city: "Datia", state: "Madhya Pradesh" },
  { city: "Daudnagar", state: "Bihar" },
  { city: "Dausa", state: "Rajasthan" },
  { city: "Davangere", state: "Karnataka" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Dehri", state: "Bihar" },
  { city: "Deogarh", state: "Odisha" },
  { city: "Deoghar", state: "Jharkhand" },
  { city: "Deoria", state: "Uttar Pradesh" },
  { city: "Desri", state: "Bihar" },
  { city: "Devbhoomi Dwarka", state: "Gujarat" },
  { city: "Dewas", state: "Madhya Pradesh" },
  { city: "Dhalai", state: "Tripura" },
  { city: "Dhamtari", state: "Chhattisgarh" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Dhar", state: "Madhya Pradesh" },
  { city: "Dharmapuri", state: "Tamil Nadu" },
  { city: "Dharwad", state: "Karnataka" },
  { city: "Dhemaji", state: "Assam" },
  { city: "Dholpur", state: "Rajasthan" },
  { city: "Dhubri", state: "Assam" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Dibang Valley", state: "Arunachal Pradesh" },
  { city: "Dibrugarh", state: "Assam" },
  { city: "Dighwara", state: "Bihar" },
  { city: "Dimapur", state: "Nagaland" },
  { city: "Dima Hasao", state: "Assam" },
  { city: "Dindigul", state: "Tamil Nadu" },
  { city: "Dindori", state: "Madhya Pradesh" },
  { city: "Diu", state: "Daman and Diu (UT)" },
  { city: "Dobhi", state: "Bihar" },
  { city: "Doda", state: "Jammu and Kashmir" },
  { city: "Dumka", state: "Jharkhand" },
  { city: "Dumra", state: "Bihar" },
  { city: "Dungarpur", state: "Rajasthan" },
  { city: "Durg", state: "Chhattisgarh" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "East Champaran", state: "Bihar" },
  { city: "East Delhi", state: "Delhi (NCT)" },
  { city: "East Garo Hills", state: "Meghalaya" },
  { city: "East Godavari", state: "Andhra Pradesh" },
  { city: "East Jaintia Hills", state: "Meghalaya" },
  { city: "East Kameng", state: "Arunachal Pradesh" },
  { city: "East Khasi Hills", state: "Meghalaya" },
  { city: "East Siang", state: "Arunachal Pradesh" },
  { city: "East Sikkim", state: "Sikkim" },
  { city: "East Singhbhum", state: "Jharkhand" },
  { city: "Ekma", state: "Bihar" },
  { city: "Ernakulam", state: "Kerala" },
  { city: "Erode", state: "Tamil Nadu" },
  { city: "Etah", state: "Uttar Pradesh" },
  { city: "Etawah", state: "Uttar Pradesh" },
  { city: "Faizabad", state: "Uttar Pradesh" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Faridkot", state: "Punjab" },
  { city: "Farrukhabad", state: "Uttar Pradesh" },
  { city: "Fatehabad", state: "Haryana" },
  { city: "Fatehgarh Sahib", state: "Punjab" },
  { city: "Fatehpur", state: "Uttar Pradesh" },
  { city: "Fatwah", state: "Bihar" },
  { city: "Fazilka", state: "Punjab" },
  { city: "Ferozepur", state: "Punjab" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Forbesganj", state: "Bihar" },
  { city: "Gadag", state: "Karnataka" },
  { city: "Gadchiroli", state: "Maharashtra" },
  { city: "Gajapati", state: "Odisha" },
  { city: "Ganderbal", state: "Jammu and Kashmir" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Ganganagar", state: "Rajasthan" },
  { city: "Gangtok", state: "Sikkim" },
  { city: "Ganjam", state: "Odisha" },
  { city: "Garhwa", state: "Jharkhand" },
  { city: "Gariyaband", state: "Chhattisgarh" },
  { city: "Gautam Buddha Nagar", state: "Uttar Pradesh" },
  { city: "Gaya", state: "Bihar" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Ghazipur", state: "Uttar Pradesh" },
  { city: "Ghoshi", state: "Bihar" },
  { city: "Giridih", state: "Jharkhand" },
  { city: "Gir Somnath", state: "Gujarat" },
  { city: "Goalpara", state: "Assam" },
  { city: "Godda", state: "Jharkhand" },
  { city: "Golaghat", state: "Assam" },
  { city: "Gomati", state: "Tripura" },
  { city: "Gonda", state: "Uttar Pradesh" },
  { city: "Gondia", state: "Maharashtra" },
  { city: "Gopalganj", state: "Bihar" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Gumla", state: "Jharkhand" },
  { city: "Guna", state: "Madhya Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Gurdaspur", state: "Punjab" },
  { city: "Gurgaon", state: "Haryana" },
  { city: "Guwahati", state: "Assam" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Hailakandi", state: "Assam" },
  { city: "Hajipur", state: "Bihar" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Hamirpur", state: "Himachal Pradesh" },
  { city: "Hamirpur", state: "Uttar Pradesh" },
  { city: "Hanumangarh", state: "Rajasthan" },
  { city: "Hapur", state: "Uttar Pradesh" },
  { city: "Harda", state: "Madhya Pradesh" },
  { city: "Hardoi", state: "Uttar Pradesh" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Hassan", state: "Karnataka" },
  { city: "Hathras", state: "Uttar Pradesh" },
  { city: "Haveri", state: "Karnataka" },
  { city: "Hazaribag", state: "Jharkhand" },
  { city: "Hilsa", state: "Bihar" },
  { city: "Hingoli", state: "Maharashtra" },
  { city: "Hisar", state: "Haryana" },
  { city: "Hojai", state: "Assam" },
  { city: "Hooghly", state: "West Bengal" },
  { city: "Hoshangabad", state: "Madhya Pradesh" },
  { city: "Hoshiarpur", state: "Punjab" },
  { city: "Howrah", state: "West Bengal" },
  { city: "Hubli", state: "Karnataka" },
  { city: "Hulasganj", state: "Bihar" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Idukki", state: "Kerala" },
  { city: "Imamganj", state: "Bihar" },
  { city: "Imphal East", state: "Manipur" },
  { city: "Imphal West", state: "Manipur" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Islampur", state: "Bihar" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Jagatsinghapur", state: "Odisha" },
  { city: "Jagdishpur", state: "Bihar" },
  { city: "Jagtial", state: "Telangana" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Jaisalmer", state: "Rajasthan" },
  { city: "Jajpur", state: "Odisha" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Jalaun", state: "Uttar Pradesh" },
  { city: "Jalgaon", state: "Maharashtra" },
  { city: "Jalna", state: "Maharashtra" },
  { city: "Jalpaiguri", state: "West Bengal" },
  { city: "Jamalpur", state: "Bihar" },
  { city: "Jammu", state: "Jammu and Kashmir" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Jamtara", state: "Jharkhand" },
  { city: "Jamui", state: "Bihar" },
  { city: "Jandaha", state: "Bihar" },
  { city: "Jangaon", state: "Telangana" },
  { city: "Janjgir-Champa", state: "Chhattisgarh" },
  { city: "Jashpur", state: "Chhattisgarh" },
  { city: "Jaunpur", state: "Uttar Pradesh" },
  { city: "Jayashankar Bhoopalpally", state: "Telangana" },
  { city: "Jaynagar", state: "Bihar" },
  { city: "Jehanabad", state: "Bihar" },
  { city: "Jhabua", state: "Madhya Pradesh" },
  { city: "Jhajha", state: "Bihar" },
  { city: "Jhajjar", state: "Haryana" },
  { city: "Jhalawar", state: "Rajasthan" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Jhanjharpur", state: "Bihar" },
  { city: "Jharsuguda", state: "Odisha" },
  { city: "Jhunjhunu", state: "Rajasthan" },
  { city: "Jind", state: "Haryana" },
  { city: "Jiribam", state: "Manipur" },
  { city: "Jogulamba Gadwal", state: "Telangana" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Jokihat", state: "Bihar" },
  { city: "Jorhat", state: "Assam" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Kabirdham (Kawardha)", state: "Chhattisgarh" },
  { city: "Kachchh", state: "Gujarat" },
  { city: "Kadmath", state: "Lakshadweep (UT)" },
  { city: "Kahalgaon", state: "Bihar" },
  { city: "Kaimur", state: "Bihar" },
  { city: "Kaithal", state: "Haryana" },
  { city: "Kakching", state: "Manipur" },
  { city: "Kalaburagi (Gulbarga)", state: "Karnataka" },
  { city: "Kalahandi", state: "Odisha" },
  { city: "Kalimpong", state: "West Bengal" },
  { city: "Kalpeni", state: "Lakshadweep (UT)" },
  { city: "Kamareddy", state: "Telangana" },
  { city: "Kamarhati", state: "West Bengal" },
  { city: "Kamjong", state: "Manipur" },
  { city: "Kamrup Metropolitan", state: "Assam" },
  { city: "Kamrup", state: "Assam" },
  { city: "Kanchipuram", state: "Tamil Nadu" },
  { city: "Kandhamal", state: "Odisha" },
  { city: "Kangra", state: "Himachal Pradesh" },
  { city: "Kanker", state: "Chhattisgarh" },
  { city: "Kannauj", state: "Uttar Pradesh" },
  { city: "Kannur", state: "Kerala" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Kanti", state: "Bihar" },
  { city: "Kanyakumari", state: "Tamil Nadu" },
  { city: "Kapurthala", state: "Punjab" },
  { city: "Karbi Anglong", state: "Assam" },
  { city: "Kargil", state: "Jammu and Kashmir" },
  { city: "Karimganj", state: "Assam" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Karur", state: "Tamil Nadu" },
  { city: "Kasaragod", state: "Kerala" },
  { city: "Kasganj", state: "Uttar Pradesh" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Kathua", state: "Jammu and Kashmir" },
  { city: "Katihar", state: "Bihar" },
  { city: "Katni", state: "Madhya Pradesh" },
  { city: "Katoria", state: "Bihar" },
  { city: "Kaushambi", state: "Uttar Pradesh" },
  { city: "Kavaratti", state: "Lakshadweep (UT)" },
  { city: "Kendrapara", state: "Odisha" },
  { city: "Kendujhar (Keonjhar)", state: "Odisha" },
  { city: "Khagaria", state: "Bihar" },
  { city: "Khagaul", state: "Bihar" },
  { city: "Khammam", state: "Telangana" },
  { city: "Khandwa", state: "Madhya Pradesh" },
  { city: "Khargone", state: "Madhya Pradesh" },
  { city: "Kheda (Nadiad)", state: "Gujarat" },
  { city: "Khunti", state: "Jharkhand" },
  { city: "Khowai", state: "Tripura" },
  { city: "Kinnaur", state: "Himachal Pradesh" },
  { city: "Kiphire", state: "Nagaland" },
  { city: "Kishanganj", state: "Bihar" },
  { city: "Kishtwar", state: "Jammu and Kashmir" },
  { city: "Kochi", state: "Kerala" },
  { city: "Kochadhaman", state: "Bihar" },
  { city: "Kodagu", state: "Karnataka" },
  { city: "Koderma", state: "Jharkhand" },
  { city: "Kohima", state: "Nagaland" },
  { city: "Kokrajhar", state: "Assam" },
  { city: "Kolar", state: "Karnataka" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Kollam", state: "Kerala" },
  { city: "Kondagaon", state: "Chhattisgarh" },
  { city: "Koppal", state: "Karnataka" },
  { city: "Koraput", state: "Odisha" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Korea (Koriya)", state: "Chhattisgarh" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Kothagudem", state: "Telangana" },
  { city: "Kottayam", state: "Kerala" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Krishna", state: "Andhra Pradesh" },
  { city: "Krishnagiri", state: "Tamil Nadu" },
  { city: "Kudra", state: "Bihar" },
  { city: "Kulgam", state: "Jammu and Kashmir" },
  { city: "Kullu", state: "Himachal Pradesh" },
  { city: "Kulu", state: "Himachal Pradesh" },
  { city: "Kupwara", state: "Jammu and Kashmir" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Kurukshetra", state: "Haryana" },
  { city: "Kurung Kumey", state: "Arunachal Pradesh" },
  { city: "Kushinagar", state: "Uttar Pradesh" },
  { city: "Lahaul & Spiti", state: "Himachal Pradesh" },
  { city: "Laheriasarai", state: "Bihar" },
  { city: "Lakhimpur", state: "Assam" },
  { city: "Lakhimpur", state: "Uttar Pradesh" },
  { city: "Lakhisarai", state: "Bihar" },
  { city: "Lalitpur", state: "Uttar Pradesh" },
  { city: "Lalganj", state: "Bihar" },
  { city: "Latehar", state: "Jharkhand" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Lauriya", state: "Bihar" },
  { city: "Lawngtlai", state: "Mizoram" },
  { city: "Leh", state: "Jammu and Kashmir" },
  { city: "Lohardaga", state: "Jharkhand" },
  { city: "Lohit", state: "Arunachal Pradesh" },
  { city: "Longding", state: "Arunachal Pradesh" },
  { city: "Longleng", state: "Nagaland" },
  { city: "Lower Dibang Valley", state: "Arunachal Pradesh" },
  { city: "Lower Siang", state: "Arunachal Pradesh" },
  { city: "Lower Subansiri", state: "Arunachal Pradesh" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Lunglei", state: "Mizoram" },
  { city: "Madhepura", state: "Bihar" },
  { city: "Madhubani", state: "Bihar" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Mahabubnagar", state: "Telangana" },
  { city: "Maharajganj", state: "Uttar Pradesh" },
  { city: "Mahasamund", state: "Chhattisgarh" },
  { city: "Mahe", state: "Puducherry (UT)" },
  { city: "Mahendragarh", state: "Haryana" },
  { city: "Maheshtala", state: "West Bengal" },
  { city: "Mahisagar", state: "Gujarat" },
  { city: "Mahua", state: "Bihar" },
  { city: "Mainatand", state: "Bihar" },
  { city: "Mainpuri", state: "Uttar Pradesh" },
  { city: "Majuli", state: "Assam" },
  { city: "Makhdumpur", state: "Bihar" },
  { city: "Malappuram", state: "Kerala" },
  { city: "Malda", state: "West Bengal" },
  { city: "Malkangiri", state: "Odisha" },
  { city: "Mamit", state: "Mizoram" },
  { city: "Manali", state: "Himachal Pradesh" },
  { city: "Mancherial", state: "Telangana" },
  { city: "Mandi", state: "Himachal Pradesh" },
  { city: "Mandla", state: "Madhya Pradesh" },
  { city: "Mandsaur", state: "Madhya Pradesh" },
  { city: "Mandya", state: "Karnataka" },
  { city: "Maner", state: "Bihar" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Mansa", state: "Punjab" },
  { city: "Mansi", state: "Bihar" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Mau", state: "Uttar Pradesh" },
  { city: "Mayurbhanj", state: "Odisha" },
  { city: "Medak", state: "Telangana" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Mehsana", state: "Gujarat" },
  { city: "Mewat", state: "Haryana" },
  { city: "Minicoy", state: "Lakshadweep (UT)" },
  { city: "Mirzapur", state: "Uttar Pradesh" },
  { city: "Moga", state: "Punjab" },
  { city: "Mohali", state: "Punjab" },
  { city: "Mohania", state: "Bihar" },
  { city: "Mohiuddinagar", state: "Bihar" },
  { city: "Mokama", state: "Bihar" },
  { city: "Mokokchung", state: "Nagaland" },
  { city: "Mon", state: "Nagaland" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Morbi", state: "Gujarat" },
  { city: "Morena", state: "Madhya Pradesh" },
  { city: "Morigaon", state: "Assam" },
  { city: "Motihari", state: "Bihar" },
  { city: "Motipur", state: "Bihar" },
  { city: "Muktsar", state: "Punjab" },
  { city: "Mumbai City", state: "Maharashtra" },
  { city: "Mumbai Suburban", state: "Maharashtra" },
  { city: "Munger", state: "Bihar" },
  { city: "Mungeli", state: "Chhattisgarh" },
  { city: "Murliganj", state: "Bihar" },
  { city: "Murshidabad", state: "West Bengal" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Mysuru (Mysore)", state: "Karnataka" },
  { city: "Nabarangpur", state: "Odisha" },
  { city: "Nadia", state: "West Bengal" },
  { city: "Nagapattinam", state: "Tamil Nadu" },
  { city: "Nagaon", state: "Assam" },
  { city: "Nagarkurnool", state: "Telangana" },
  { city: "Nagaur", state: "Rajasthan" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Nainital", state: "Uttarakhand" },
  { city: "Nalanda", state: "Bihar" },
  { city: "Nalbari", state: "Assam" },
  { city: "Nalgonda", state: "Telangana" },
  { city: "Namakkal", state: "Tamil Nadu" },
  { city: "Namsai", state: "Arunachal Pradesh" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Nandurbar", state: "Maharashtra" },
  { city: "Narayanpur", state: "Chhattisgarh" },
  { city: "Narkatiaganj", state: "Bihar" },
  { city: "Narmada (Rajpipla)", state: "Gujarat" },
  { city: "Narpatganj", state: "Bihar" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Nasriganj", state: "Bihar" },
  { city: "Navsari", state: "Gujarat" },
  { city: "Nawada", state: "Bihar" },
  { city: "Nawanshahr", state: "Punjab" },
  { city: "Nayagarh", state: "Odisha" },
  { city: "Neemuch", state: "Madhya Pradesh" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "New Delhi", state: "Delhi (NCT)" },
  { city: "Nilgiris", state: "Tamil Nadu" },
  { city: "Nirmal", state: "Telangana" },
  { city: "Nirmali", state: "Bihar" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Nokha", state: "Bihar" },
  { city: "North 24 Parganas", state: "West Bengal" },
  { city: "North Delhi", state: "Delhi (NCT)" },
  { city: "North East Delhi", state: "Delhi (NCT)" },
  { city: "North Garo Hills", state: "Meghalaya" },
  { city: "North Goa", state: "Goa" },
  { city: "North Sikkim", state: "Sikkim" },
  { city: "North Tripura", state: "Tripura" },
  { city: "North West Delhi", state: "Delhi (NCT)" },
  { city: "Nuapada", state: "Odisha" },
  { city: "Obra", state: "Bihar" },
  { city: "Osmanabad", state: "Maharashtra" },
  { city: "Pakur", state: "Jharkhand" },
  { city: "Palakkad", state: "Kerala" },
  { city: "Palamu", state: "Jharkhand" },
  { city: "Palghar", state: "Maharashtra" },
  { city: "Palhalan", state: "Jammu and Kashmir" },
  { city: "Pali", state: "Rajasthan" },
  { city: "Palwal", state: "Haryana" },
  { city: "Panaji", state: "Goa" },
  { city: "Panchkula", state: "Haryana" },
  { city: "Panchmahal (Godhra)", state: "Gujarat" },
  { city: "Panihati", state: "West Bengal" },
  { city: "Panipat", state: "Haryana" },
  { city: "Panna", state: "Madhya Pradesh" },
  { city: "Papum Pare", state: "Arunachal Pradesh" },
  { city: "Parbhani", state: "Maharashtra" },
  { city: "Patan", state: "Gujarat" },
  { city: "Pathanamthitta", state: "Kerala" },
  { city: "Pathankot", state: "Punjab" },
  { city: "Patiala", state: "Punjab" },
  { city: "Patna Sahib", state: "Bihar" },
  { city: "Patna", state: "Bihar" },
  { city: "Pauri Garhwal", state: "Uttarakhand" },
  { city: "Peddapalli", state: "Telangana" },
  { city: "Perambalur", state: "Tamil Nadu" },
  { city: "Peren", state: "Nagaland" },
  { city: "Phagwara", state: "Punjab" },
  { city: "Phek", state: "Nagaland" },
  { city: "Phulparas", state: "Bihar" },
  { city: "Phulwari Sharif", state: "Bihar" },
  { city: "Pilibhit", state: "Uttar Pradesh" },
  { city: "Piprahi", state: "Bihar" },
  { city: "Piro", state: "Bihar" },
  { city: "Pithoragarh", state: "Uttarakhand" },
  { city: "Ponda", state: "Goa" },
  { city: "Pondicherry", state: "Puducherry (UT)" },
  { city: "Poonch", state: "Jammu and Kashmir" },
  { city: "Porbandar", state: "Gujarat" },
  { city: "Prakasam", state: "Andhra Pradesh" },
  { city: "Pratapgarh", state: "Rajasthan" },
  { city: "Pratapgarh", state: "Uttar Pradesh" },
  { city: "Puducherry", state: "Puducherry (UT)" },
  { city: "Pudukkottai", state: "Tamil Nadu" },
  { city: "Pulwama", state: "Jammu and Kashmir" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Pupri", state: "Bihar" },
  { city: "Puri", state: "Odisha" },
  { city: "Purnia", state: "Bihar" },
  { city: "Purulia", state: "West Bengal" },
  { city: "RaeBareli", state: "Uttar Pradesh" },
  { city: "Rafiganj", state: "Bihar" },
  { city: "Raghopur", state: "Bihar" },
  { city: "Raigarh", state: "Chhattisgarh" },
  { city: "Raigad", state: "Maharashtra" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Raisen", state: "Madhya Pradesh" },
  { city: "Rajgarh", state: "Madhya Pradesh" },
  { city: "Rajgir", state: "Bihar" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Rajouri", state: "Jammu and Kashmir" },
  { city: "Rajpur Sonarpur", state: "West Bengal" },
  { city: "Rajsamand", state: "Rajasthan" },
  { city: "Ramanagara", state: "Karnataka" },
  { city: "Ramanathapuram", state: "Tamil Nadu" },
  { city: "Ramban", state: "Jammu and Kashmir" },
  { city: "Ramgarh", state: "Bihar" },
  { city: "Ramgarh", state: "Jharkhand" },
  { city: "Rampur", state: "Uttar Pradesh" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Rangareddy", state: "Telangana" },
  { city: "Raniganj", state: "Bihar" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Ratnagiri", state: "Maharashtra" },
  { city: "Raxaul", state: "Bihar" },
  { city: "Reasi", state: "Jammu and Kashmir" },
  { city: "Revelganj", state: "Bihar" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Rewari", state: "Haryana" },
  { city: "Ri Bhoi", state: "Meghalaya" },
  { city: "Riga", state: "Bihar" },
  { city: "Rishikesh", state: "Uttarakhand" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Rohtas", state: "Bihar" },
  { city: "Roorkee", state: "Uttarakhand" },
  { city: "Rosera", state: "Bihar" },
  { city: "Rudraprayag", state: "Uttarakhand" },
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Rupauli", state: "Bihar" },
  { city: "Rupnagar", state: "Punjab" },
  { city: "Sabarkantha (Himmatnagar)", state: "Gujarat" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Saharsa", state: "Bihar" },
  { city: "Sahibganj", state: "Jharkhand" },
  { city: "Saiha", state: "Mizoram" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Samastipur", state: "Bihar" },
  { city: "Samba", state: "Jammu and Kashmir" },
  { city: "Sambalpur", state: "Odisha" },
  { city: "Sambhal", state: "Uttar Pradesh" },
  { city: "Sandesh", state: "Bihar" },
  { city: "Sangareddy", state: "Telangana" },
  { city: "Sangli", state: "Maharashtra" },
  { city: "Sangrur", state: "Punjab" },
  { city: "Sant Kabir Nagar", state: "Uttar Pradesh" },
  { city: "Saraigarh", state: "Bihar" },
  { city: "Saran", state: "Bihar" },
  { city: "Sasaram", state: "Bihar" },
  { city: "Satara", state: "Maharashtra" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Sawai Madhopur", state: "Rajasthan" },
  { city: "Sehore", state: "Madhya Pradesh" },
  { city: "Senapati", state: "Manipur" },
  { city: "Seoni", state: "Madhya Pradesh" },
  { city: "Sepahijala", state: "Tripura" },
  { city: "Seraikela-Kharsawan", state: "Jharkhand" },
  { city: "Serchhip", state: "Mizoram" },
  { city: "Shahdara", state: "Delhi (NCT)" },
  { city: "Shahdol", state: "Madhya Pradesh" },
  { city: "Shahjahanpur", state: "Uttar Pradesh" },
  { city: "Shahpur", state: "Bihar" },
  { city: "Shajapur", state: "Madhya Pradesh" },
  { city: "Sheikhpura", state: "Bihar" },
  { city: "Sheopur", state: "Madhya Pradesh" },
  { city: "Sheohar", state: "Bihar" },
  { city: "Sherghati", state: "Bihar" },
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Shopian", state: "Jammu and Kashmir" },
  { city: "Shravasti", state: "Uttar Pradesh" },
  { city: "Siang", state: "Arunachal Pradesh" },
  { city: "Siddharth Nagar", state: "Uttar Pradesh" },
  { city: "Siddipet", state: "Telangana" },
  { city: "Sidhi", state: "Madhya Pradesh" },
  { city: "Sikandra", state: "Bihar" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Simdega", state: "Jharkhand" },
  { city: "Sindhudurg", state: "Maharashtra" },
  { city: "Singheshwar", state: "Bihar" },
  { city: "Singrauli", state: "Madhya Pradesh" },
  { city: "Sirmaur (Sirmour)", state: "Himachal Pradesh" },
  { city: "Sirohi", state: "Rajasthan" },
  { city: "Sirsa", state: "Haryana" },
  { city: "Sitamarhi", state: "Bihar" },
  { city: "Sitapur", state: "Uttar Pradesh" },
  { city: "Sivaganga", state: "Tamil Nadu" },
  { city: "Sivasagar", state: "Assam" },
  { city: "Siwan", state: "Bihar" },
  { city: "Solan", state: "Himachal Pradesh" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Sonbhadra", state: "Uttar Pradesh" },
  { city: "Sonepur", state: "Odisha" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Sonitpur", state: "Assam" },
  { city: "Sono", state: "Bihar" },
  { city: "South 24 Parganas", state: "West Bengal" },
  { city: "South Delhi", state: "Delhi (NCT)" },
  { city: "South East Delhi", state: "Delhi (NCT)" },
  { city: "South Garo Hills", state: "Meghalaya" },
  { city: "South Goa", state: "Goa" },
  { city: "South Salmara-Mankachar", state: "Assam" },
  { city: "South Sikkim", state: "Sikkim" },
  { city: "South Tripura", state: "Tripura" },
  { city: "South West Delhi", state: "Delhi (NCT)" },
  { city: "South West Garo Hills", state: "Meghalaya" },
  { city: "South West Khasi Hills", state: "Meghalaya" },
  { city: "Sri Ganganagar", state: "Rajasthan" },
  { city: "Srikakulam", state: "Andhra Pradesh" },
  { city: "Srinagar", state: "Jammu and Kashmir" },
  { city: "Sugauli", state: "Bihar" },
  { city: "Sultanpur", state: "Uttar Pradesh" },
  { city: "Sultanganj", state: "Bihar" },
  { city: "Sundargarh", state: "Odisha" },
  { city: "Supaul", state: "Bihar" },
  { city: "Surajpur", state: "Chhattisgarh" },
  { city: "Surat", state: "Gujarat" },
  { city: "Surendranagar", state: "Gujarat" },
  { city: "Surguja", state: "Chhattisgarh" },
  { city: "Suryapet", state: "Telangana" },
  { city: "Tajpur", state: "Bihar" },
  { city: "Tamil Nadu", state: "Tamil Nadu" },
  { city: "Tapi (Vyara)", state: "Gujarat" },
  { city: "Tariani", state: "Bihar" },
  { city: "Tawang", state: "Arunachal Pradesh" },
  { city: "Tehri Garhwal", state: "Uttarakhand" },
  { city: "Tekari", state: "Bihar" },
  { city: "Telangana", state: "Telangana" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Thanjavur", state: "Tamil Nadu" },
  { city: "Thakurganj", state: "Bihar" },
  { city: "Theni", state: "Tamil Nadu" },
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Thoothukudi", state: "Tamil Nadu" },
  { city: "Thoubal", state: "Manipur" },
  { city: "Thrissur", state: "Kerala" },
  { city: "Tikamgarh", state: "Madhya Pradesh" },
  { city: "Tinsukia", state: "Assam" },
  { city: "Tirap", state: "Arunachal Pradesh" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Tiruvallur", state: "Tamil Nadu" },
  { city: "Tiruvannamalai", state: "Tamil Nadu" },
  { city: "Tiruvarur", state: "Tamil Nadu" },
  { city: "Tonk", state: "Rajasthan" },
  { city: "Tripura", state: "Tripura" },
  { city: "Triveniganj", state: "Bihar" },
  { city: "Tumakuru (Tumkur)", state: "Karnataka" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Udalguri", state: "Assam" },
  { city: "Udhampur", state: "Jammu and Kashmir" },
  { city: "Udham Singh Nagar", state: "Uttarakhand" },
  { city: "Udupi", state: "Karnataka" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Ukhrul", state: "Manipur" },
  { city: "Una", state: "Himachal Pradesh" },
  { city: "Unakoti", state: "Tripura" },
  { city: "Unnao", state: "Uttar Pradesh" },
  { city: "Upper Dibang Valley", state: "Arunachal Pradesh" },
  { city: "Upper Siang", state: "Arunachal Pradesh" },
  { city: "Upper Subansiri", state: "Arunachal Pradesh" },
  { city: "Uttar Dinajpur", state: "West Bengal" },
  { city: "Uttarkashi", state: "Uttarakhand" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Vaishali", state: "Bihar" },
  { city: "Valmiki Nagar", state: "Bihar" },
  { city: "Valsad", state: "Gujarat" },
  { city: "Vasco da Gama", state: "Goa" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Vellore", state: "Tamil Nadu" },
  { city: "Vidisha", state: "Madhya Pradesh" },
  { city: "Vijayapura", state: "Karnataka" },
  { city: "Viluppuram", state: "Tamil Nadu" },
  { city: "Virudhunagar", state: "Tamil Nadu" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Vizianagaram", state: "Andhra Pradesh" },
  { city: "Wanaparthy", state: "Telangana" },
  { city: "Warangal", state: "Telangana" },
  { city: "Wardha", state: "Maharashtra" },
  { city: "Washim", state: "Maharashtra" },
  { city: "Wayanad", state: "Kerala" },
  { city: "Wazirganj", state: "Bihar" },
  { city: "West Champaran", state: "Bihar" },
  { city: "West Delhi", state: "Delhi (NCT)" },
  { city: "West Garo Hills", state: "Meghalaya" },
  { city: "West Godavari", state: "Andhra Pradesh" },
  { city: "West Jaintia Hills", state: "Meghalaya" },
  { city: "West Kameng", state: "Arunachal Pradesh" },
  { city: "West Karbi Anglong", state: "Assam" },
  { city: "West Khasi Hills", state: "Meghalaya" },
  { city: "West Siang", state: "Arunachal Pradesh" },
  { city: "West Sikkim", state: "Sikkim" },
  { city: "West Singhbhum", state: "Jharkhand" },
  { city: "West Tripura", state: "Tripura" },
  { city: "Wokha", state: "Nagaland" },
  { city: "Yadadri Bhuvanagiri", state: "Telangana" },
  { city: "Yadgir", state: "Karnataka" },
  { city: "Yamunanagar", state: "Haryana" },
  { city: "Yavatmal", state: "Maharashtra" },
  { city: "Zunheboto", state: "Nagaland" }
].sort((a, b) => a.city.localeCompare(b.city));
