import { Artist } from "@/types";

export const artists: Artist[] = [
  {
    id: "a1",
    name: "Aarav Sharma",
    profilePhoto: "https://i.pravatar.cc/800?img=2",
    coverPhoto: "https://picsum.photos/seed/aarav/800/400",
    roles: ["Actor", "Model"],
    city: "Mumbai",
    state: "Maharashtra",
    languages: ["Hindi", "English", "Marathi"],
    bio: "Passionate method actor with 5 years of theater experience. Looking for challenging leading roles in independent cinema.",
    skills: ["Method Acting", "Dance", "Voice Over", "Stage Combat"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p1/400/400",
      "https://picsum.photos/seed/p2/400/400",
      "https://picsum.photos/seed/p3/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 1240,
    rating: 4.8,
    reviewCount: 34,
    joinedDate: "2023-01-15T00:00:00.000Z",
    experience: "5 years",
    availability: true
  },
  {
    id: "a2",
    name: "Priya Patel",
    profilePhoto: "https://i.pravatar.cc/800?img=3",
    coverPhoto: "https://picsum.photos/seed/priya/800/400",
    roles: ["Singer", "Musician"],
    city: "Delhi",
    state: "Delhi",
    languages: ["Hindi", "English", "Punjabi"],
    bio: "Classically trained vocalist blending traditional ragas with modern electronic beats.",
    skills: ["Hindustani Classical", "Carnatic Music", "Guitar", "Music Production"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p4/400/400",
      "https://picsum.photos/seed/p5/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 890,
    rating: 5.0,
    reviewCount: 12,
    joinedDate: "2023-03-22T00:00:00.000Z",
    experience: "8 years",
    availability: false
  },
  {
    id: "a3",
    name: "Vikram Singh",
    profilePhoto: "https://i.pravatar.cc/800?img=4",
    coverPhoto: "https://picsum.photos/seed/vikram/800/400",
    roles: ["Director", "Writer"],
    city: "Bangalore",
    state: "Karnataka",
    languages: ["English", "Kannada", "Hindi"],
    bio: "Award-winning short film director focused on gritty urban narratives.",
    skills: ["Screenwriting", "Directing", "Cinematography", "Video Editing"],
    portfolioImages: [],
    subscriptionStatus: "EXPIRED",
    isVerified: false,
    profileViews: 450,
    rating: 4.2,
    reviewCount: 5,
    joinedDate: "2022-11-05T00:00:00.000Z",
    experience: "10 years",
    availability: true
  },
  {
    id: "a4",
    name: "Neha Gupta",
    profilePhoto: "https://i.pravatar.cc/800?img=5",
    coverPhoto: "https://picsum.photos/seed/neha/800/400",
    roles: ["Dancer", "Choreographer"],
    city: "Hyderabad",
    state: "Telangana",
    languages: ["Telugu", "Hindi", "English"],
    bio: "Contemporary dancer specializing in Bollywood and Hip-Hop fusion.",
    skills: ["Bollywood", "Hip-Hop", "Contemporary", "Salsa"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p6/400/400",
      "https://picsum.photos/seed/p7/400/400",
      "https://picsum.photos/seed/p8/400/400",
      "https://picsum.photos/seed/p9/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 2100,
    rating: 4.9,
    reviewCount: 56,
    joinedDate: "2023-05-10T00:00:00.000Z",
    experience: "7 years",
    availability: true
  },
  {
    id: "a5",
    name: "Rahul Desai",
    profilePhoto: "https://i.pravatar.cc/800?img=6",
    coverPhoto: "https://picsum.photos/seed/rahul/800/400",
    roles: ["Cameraman", "DOP"],
    city: "Chennai",
    state: "Tamil Nadu",
    languages: ["Tamil", "English"],
    bio: "Experienced Director of Photography with a keen eye for lighting and composition.",
    skills: ["Cinematography", "Lighting", "Drone Operation", "Red Camera"],
    portfolioImages: [
      "https://picsum.photos/seed/p10/400/400",
      "https://picsum.photos/seed/p11/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 750,
    rating: 4.7,
    reviewCount: 20,
    joinedDate: "2022-08-18T00:00:00.000Z",
    experience: "12 years",
    availability: true
  },
  {
    id: "a6",
    name: "Ananya Kapoor",
    profilePhoto: "https://i.pravatar.cc/800?img=7",
    coverPhoto: "https://picsum.photos/seed/ananya/800/400",
    roles: ["VFX Artist", "Colorist"],
    city: "Kolkata",
    state: "West Bengal",
    languages: ["Bengali", "English", "Hindi"],
    bio: "Visual Effects maestro bringing imagination to life pixel by pixel.",
    skills: ["After Effects", "Nuke", "DaVinci Resolve", "3D Animation"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [],
    subscriptionStatus: "ACTIVE",
    isVerified: false,
    profileViews: 320,
    rating: 4.5,
    reviewCount: 8,
    joinedDate: "2023-09-01T00:00:00.000Z",
    experience: "4 years",
    availability: true
  },
  {
    id: "a7",
    name: "Kabir Khan",
    profilePhoto: "https://i.pravatar.cc/800?img=8",
    coverPhoto: "https://picsum.photos/seed/kabir/800/400",
    roles: ["Editor", "Sound Designer"],
    city: "Patna",
    state: "Bihar",
    languages: ["Bhojpuri", "Hindi", "English"],
    bio: "Crafting compelling narratives through pace and rhythm in the edit room.",
    skills: ["Premiere Pro", "Final Cut Pro", "Pro Tools", "Audio Mixing"],
    portfolioImages: [],
    subscriptionStatus: "EXPIRED",
    isVerified: false,
    profileViews: 150,
    rating: 4.1,
    reviewCount: 3,
    joinedDate: "2024-01-20T00:00:00.000Z",
    experience: "2 years",
    availability: true
  },
  {
    id: "a8",
    name: "Meera Reddy",
    profilePhoto: "https://i.pravatar.cc/800?img=9",
    coverPhoto: "https://picsum.photos/seed/meera/800/400",
    roles: ["Casting Director"],
    city: "Lucknow",
    state: "Uttar Pradesh",
    languages: ["Hindi", "Urdu", "English"],
    bio: "Finding the perfect face for every character.",
    skills: ["Talent Scouting", "Auditioning", "Contract Negotiation", "Script Analysis"],
    portfolioImages: [],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 980,
    rating: 4.9,
    reviewCount: 45,
    joinedDate: "2021-05-12T00:00:00.000Z",
    experience: "15 years",
    availability: false
  },
  {
    id: "a9",
    name: "Rohan Joshi",
    profilePhoto: "https://i.pravatar.cc/800?img=10",
    coverPhoto: "https://picsum.photos/seed/rohan/800/400",
    roles: ["Stand-up Comedian", "Writer"],
    city: "Jaipur",
    state: "Rajasthan",
    languages: ["Hindi", "English", "Marwari"],
    bio: "Making people laugh awkwardly at their own insecurities since 2018.",
    skills: ["Comedy", "Scriptwriting", "Improv", "Public Speaking"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
        "https://picsum.photos/seed/p12/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 3400,
    rating: 4.6,
    reviewCount: 112,
    joinedDate: "2022-02-28T00:00:00.000Z",
    experience: "6 years",
    availability: true
  },
  {
    id: "a10",
    name: "Isha Jain",
    profilePhoto: "https://i.pravatar.cc/800?img=11",
    coverPhoto: "https://picsum.photos/seed/isha/800/400",
    roles: ["Actor", "Voice Over Artist"],
    city: "Mumbai",
    state: "Maharashtra",
    languages: ["Hindi", "English", "Gujarati"],
    bio: "Versatile actor known for intense dramatic performances and a highly adaptable voice.",
    skills: ["Acting", "Dubbing", "Voice Acting", "Mimicry"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p13/400/400",
      "https://picsum.photos/seed/p14/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: false,
    profileViews: 670,
    rating: 4.4,
    reviewCount: 19,
    joinedDate: "2023-11-15T00:00:00.000Z",
    experience: "3 years",
    availability: true
  },
  {
      id: "a11",
      name: "Siddharth Verma",
      profilePhoto: "https://i.pravatar.cc/800?img=12",
      coverPhoto: "https://picsum.photos/seed/siddharth/800/400",
      roles: ["Music Producer", "Composer"],
      city: "Delhi",
      state: "Delhi",
      languages: ["Hindi", "English"],
      bio: "Creating soundscapes that elevate visual storytelling to the next level.",
      skills: ["Logic Pro X", "Ableton Live", "Film Scoring", "Sound Design"],
      portfolioImages: [],
      subscriptionStatus: "EXPIRED",
      isVerified: false,
      profileViews: 220,
      rating: 4.0,
      reviewCount: 4,
      joinedDate: "2024-02-10T00:00:00.000Z",
      experience: "2 years",
      availability: true
  },
  {
      id: "a12",
      name: "Tara Menon",
      profilePhoto: "https://i.pravatar.cc/800?img=13",
      coverPhoto: "https://picsum.photos/seed/tara/800/400",
      roles: ["Director", "Producer"],
      city: "Bangalore",
      state: "Karnataka",
      languages: ["English", "Malayalam", "Hindi"],
      bio: "Visionary director steering independent projects from concept to distribution.",
      skills: ["Film Direction", "Line Producing", "Budgeting", "Project Management"],
      portfolioImages: [],
      subscriptionStatus: "ACTIVE",
      isVerified: true,
      profileViews: 1150,
      rating: 4.8,
      reviewCount: 31,
      joinedDate: "2021-09-25T00:00:00.000Z",
      experience: "9 years",
      availability: false
  },
  {
      id: "a13",
      name: "Arjun Das",
      profilePhoto: "https://i.pravatar.cc/800?img=14",
      coverPhoto: "https://picsum.photos/seed/arjun/800/400",
      roles: ["Dancer", "Actor"],
      city: "Hyderabad",
      state: "Telangana",
      languages: ["Telugu", "Hindi", "English"],
      bio: "Energetic performer bringing stories alive through movement and expression.",
      skills: ["Classical Dance", "Freestyle", "Acting", "Stage Performance"],
      showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      portfolioImages: [
          "https://picsum.photos/seed/p15/400/400"
      ],
      subscriptionStatus: "ACTIVE",
      isVerified: true,
      profileViews: 880,
      rating: 4.5,
      reviewCount: 22,
      joinedDate: "2023-04-05T00:00:00.000Z",
      experience: "5 years",
      availability: true
  },
  {
      id: "a14",
      name: "Kavya Singh",
      profilePhoto: "https://i.pravatar.cc/800?img=15",
      coverPhoto: "https://picsum.photos/seed/kavya/800/400",
      roles: ["Makeup Artist", "Hair Stylist"],
      city: "Mumbai",
      state: "Maharashtra",
      languages: ["Hindi", "English", "Marathi"],
      bio: "Transforming faces for camera, stage, and special FX.",
      skills: ["Bridal Makeup", "Prosthetics", "Hair Styling", "Airbrush Makeup"],
      portfolioImages: [
          "https://picsum.photos/seed/p16/400/400",
          "https://picsum.photos/seed/p17/400/400",
          "https://picsum.photos/seed/p18/400/400"
      ],
      subscriptionStatus: "ACTIVE",
      isVerified: true,
      profileViews: 1560,
      rating: 4.9,
      reviewCount: 89,
      joinedDate: "2022-06-12T00:00:00.000Z",
      experience: "8 years",
      availability: true
  },
  {
      id: "a15",
      name: "Manoj Kumar",
      profilePhoto: "https://i.pravatar.cc/800?img=16",
      coverPhoto: "https://picsum.photos/seed/manoj/800/400",
      roles: ["Art Director", "Set Designer"],
      city: "Chennai",
      state: "Tamil Nadu",
      languages: ["Tamil", "English"],
      bio: "Building immersive worlds for film and television productions.",
      skills: ["Set Design", "Prop Making", "3D Sketchup", "Budget Management"],
      portfolioImages: [
          "https://picsum.photos/seed/p19/400/400"
      ],
      subscriptionStatus: "ACTIVE",
      isVerified: false,
      profileViews: 410,
      rating: 4.3,
      reviewCount: 11,
      joinedDate: "2023-10-02T00:00:00.000Z",
      experience: "6 years",
      availability: true
  },
  {
    id: "a16",
    name: "Ravi Shankar",
    profilePhoto: "https://i.pravatar.cc/800?img=17",
    coverPhoto: "https://picsum.photos/seed/ravi/800/400",
    roles: ["Actor", "Writer"],
    city: "Kolkata",
    state: "West Bengal",
    languages: ["Bengali", "English"],
    bio: "Theater veteran bringing depth and nuance to every stage performance.",
    skills: ["Theater Acting", "Script Writing", "Directing"],
    portfolioImages: [],
    subscriptionStatus: "EXPIRED",
    isVerified: true,
    profileViews: 900,
    rating: 4.6,
    reviewCount: 40,
    joinedDate: "2021-01-10T00:00:00.000Z",
    experience: "15 years",
    availability: true
  },
  {
    id: "a17",
    name: "Smriti Irani",
    profilePhoto: "https://i.pravatar.cc/800?img=18",
    coverPhoto: "https://picsum.photos/seed/smriti/800/400",
    roles: ["Singer"],
    city: "Patna",
    state: "Bihar",
    languages: ["Hindi", "Bhojpuri"],
    bio: "Folk singer preserving traditional tunes with a modern touch.",
    skills: ["Folk Singing", "Harmonium", "Live Performance"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [],
    subscriptionStatus: "ACTIVE",
    isVerified: false,
    profileViews: 300,
    rating: 4.2,
    reviewCount: 5,
    joinedDate: "2024-02-01T00:00:00.000Z",
    experience: "3 years",
    availability: true
  },
  {
    id: "a18",
    name: "Aditya Roy",
    profilePhoto: "https://i.pravatar.cc/800?img=19",
    coverPhoto: "https://picsum.photos/seed/aditya/800/400",
    roles: ["DOP", "Cameraman"],
    city: "Lucknow",
    state: "Uttar Pradesh",
    languages: ["Hindi", "English"],
    bio: "Capturing cinematic visuals for documentaries and short films.",
    skills: ["Cinematography", "Documentary Filmmaking", "Lighting Design"],
    portfolioImages: [
      "https://picsum.photos/seed/p20/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 500,
    rating: 4.8,
    reviewCount: 18,
    joinedDate: "2022-12-05T00:00:00.000Z",
    experience: "7 years",
    availability: false
  },
  {
    id: "a19",
    name: "Naina Chopra",
    profilePhoto: "https://i.pravatar.cc/800?img=20",
    coverPhoto: "https://picsum.photos/seed/naina/800/400",
    roles: ["Editor", "VFX Artist"],
    city: "Jaipur",
    state: "Rajasthan",
    languages: ["Hindi", "English"],
    bio: "Piecing together stories with seamless transitions and stunning effects.",
    skills: ["Video Editing", "Motion Graphics", "Color Grading"],
    portfolioImages: [],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 1200,
    rating: 4.9,
    reviewCount: 60,
    joinedDate: "2021-08-15T00:00:00.000Z",
    experience: "10 years",
    availability: true
  },
  {
    id: "a20",
    name: "Karan Johar",
    profilePhoto: "https://i.pravatar.cc/800?img=21",
    coverPhoto: "https://picsum.photos/seed/karan/800/400",
    roles: ["Director", "Producer"],
    city: "Mumbai",
    state: "Maharashtra",
    languages: ["Hindi", "English"],
    bio: "Creating blockbusters that define the next generation of cinema.",
    skills: ["Film Direction", "Film Production", "Screenwriting"],
    portfolioImages: [],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 5000,
    rating: 4.7,
    reviewCount: 200,
    joinedDate: "2020-05-20T00:00:00.000Z",
    experience: "25 years",
    availability: true
  },
  {
    id: "a21",
    name: "Sanya Malhotra",
    profilePhoto: "https://i.pravatar.cc/800?img=22",
    coverPhoto: "https://picsum.photos/seed/sanya/800/400",
    roles: ["Actor", "Dancer"],
    city: "Delhi",
    state: "Delhi",
    languages: ["Hindi", "English"],
    bio: "Versatile actor known for breaking stereotypes and delivering powerful performances.",
    skills: ["Acting", "Contemporary Dance", "Voice Modulation"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p21/400/400",
      "https://picsum.photos/seed/p22/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 3000,
    rating: 4.8,
    reviewCount: 150,
    joinedDate: "2021-11-10T00:00:00.000Z",
    experience: "6 years",
    availability: false
  },
  {
    id: "a22",
    name: "Ranveer Singh",
    profilePhoto: "https://i.pravatar.cc/800?img=23",
    coverPhoto: "https://picsum.photos/seed/ranveer/800/400",
    roles: ["Actor", "Model"],
    city: "Mumbai",
    state: "Maharashtra",
    languages: ["Hindi", "English", "Marathi"],
    bio: "High-energy performer always ready to push the boundaries of conventional cinema.",
    skills: ["Acting", "Rapping", "High Energy Performance"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p23/400/400",
      "https://picsum.photos/seed/p24/400/400"
    ],
    subscriptionStatus: "EXPIRED",
    isVerified: true,
    profileViews: 4500,
    rating: 4.6,
    reviewCount: 180,
    joinedDate: "2020-02-14T00:00:00.000Z",
    experience: "12 years",
    availability: true
  },
  {
    id: "a23",
    name: "Alia Bhatt",
    profilePhoto: "https://i.pravatar.cc/800?img=24",
    coverPhoto: "https://picsum.photos/seed/alia/800/400",
    roles: ["Actor", "Singer"],
    city: "Mumbai",
    state: "Maharashtra",
    languages: ["Hindi", "English"],
    bio: "Critically acclaimed actor delivering emotionally resonant performances.",
    skills: ["Acting", "Playback Singing", "Producing"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p25/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 6000,
    rating: 4.9,
    reviewCount: 250,
    joinedDate: "2020-08-08T00:00:00.000Z",
    experience: "10 years",
    availability: true
  },
  {
    id: "a24",
    name: "Ayushmann Khurrana",
    profilePhoto: "https://i.pravatar.cc/800?img=25",
    coverPhoto: "https://picsum.photos/seed/ayushmann/800/400",
    roles: ["Actor", "Singer", "Writer"],
    city: "Mumbai",
    state: "Maharashtra",
    languages: ["Hindi", "English", "Punjabi"],
    bio: "Championing socially relevant cinema with a blend of humor and heart.",
    skills: ["Acting", "Singing", "Poetry", "Guitar"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [
      "https://picsum.photos/seed/p26/400/400"
    ],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 4000,
    rating: 4.8,
    reviewCount: 160,
    joinedDate: "2021-03-20T00:00:00.000Z",
    experience: "11 years",
    availability: false
  },
  {
    id: "a25",
    name: "A. R. Rahman",
    profilePhoto: "https://i.pravatar.cc/800?img=26",
    coverPhoto: "https://picsum.photos/seed/arrahman/800/400",
    roles: ["Musician", "Composer", "Singer"],
    city: "Chennai",
    state: "Tamil Nadu",
    languages: ["Tamil", "Hindi", "English"],
    bio: "Academy Award-winning composer bringing Indian music to the global stage.",
    skills: ["Music Direction", "Singing", "Keyboard", "Music Production"],
    showreelUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    portfolioImages: [],
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    profileViews: 10000,
    rating: 5.0,
    reviewCount: 500,
    joinedDate: "2020-01-01T00:00:00.000Z",
    experience: "30+ years",
    availability: true
  }
];
