import { Booking } from "@/types";

export const bookings: Booking[] = [
  {
    id: "b1",
    artistId: "a1", // Aarav Sharma (Actor)
    clientId: "c1",
    eventType: "Ad Shoot",
    eventDate: "2024-04-15",
    city: "Mumbai",
    duration: 8,
    amount: 15000,
    status: "CONFIRMED",
    clientName: "Tata Motors Ad Campaign",
  },
  {
    id: "b2",
    artistId: "a4", // Neha Gupta (Dancer)
    clientId: "c2",
    eventType: "Corporate Event",
    eventDate: "2024-04-20",
    city: "Hyderabad",
    duration: 2,
    amount: 25000,
    status: "PENDING",
    clientName: "Tech Mahindra Annual Day",
  },
  {
    id: "b3",
    artistId: "a2", // Priya Patel (Singer)
    clientId: "c3",
    eventType: "Wedding Sangeet",
    eventDate: "2024-05-05",
    city: "Delhi",
    duration: 3,
    amount: 50000,
    status: "COMPLETED",
    clientName: "Sharma Family Sangeet",
    clientRating: 5,
    artistRating: 5,
  },
  {
    id: "b4",
    artistId: "a9", // Rohan Joshi (Comedian)
    clientId: "c4",
    eventType: "Stand-up Show",
    eventDate: "2024-03-25",
    city: "Jaipur",
    duration: 1,
    amount: 30000,
    status: "COMPLETED",
    clientName: "Laugh Club Jaipur",
    clientRating: 4,
    artistRating: 5,
  },
  {
    id: "b5",
    artistId: "a5", // Rahul Desai (Cameraman)
    clientId: "p2", // YRF
    eventType: "Film Shoot",
    eventDate: "2024-06-01",
    city: "Mumbai",
    duration: 48, // multiple days
    amount: 120000,
    status: "CONFIRMED",
    clientName: "YRF New Project",
  },
  {
    id: "b6",
    artistId: "a1",
    clientId: "c5",
    eventType: "Short Film",
    eventDate: "2024-03-10",
    city: "Pune",
    duration: 12,
    amount: 20000,
    status: "COMPLETED",
    clientName: "Independent Filmmakers Co.",
    clientRating: 5,
  },
  {
    id: "b7",
    artistId: "a14", // Kavya Singh (Makeup)
    clientId: "c6",
    eventType: "Bridal Makeup",
    eventDate: "2024-04-22",
    city: "Mumbai",
    duration: 5,
    amount: 40000,
    status: "PENDING",
    clientName: "Priyanka's Wedding",
  },
  {
    id: "b8",
    artistId: "a25", // A.R. Rahman
    clientId: "c7",
    eventType: "Concert",
    eventDate: "2024-08-15",
    city: "Chennai",
    duration: 4,
    amount: 5000000,
    status: "CONFIRMED",
    clientName: "Independence Day Gala",
  },
  {
    id: "b9",
    artistId: "a13", // Arjun Das (Dancer)
    clientId: "c8",
    eventType: "Music Video",
    eventDate: "2024-04-05",
    city: "Hyderabad",
    duration: 10,
    amount: 15000,
    status: "CANCELLED",
    clientName: "T-Series Regional",
  },
  {
    id: "b10",
    artistId: "a10", // Isha Jain (Voice over)
    clientId: "c9",
    eventType: "Dubbing",
    eventDate: "2024-03-22",
    city: "Mumbai",
    duration: 4,
    amount: 8000,
    status: "COMPLETED",
    clientName: "Netflix India Localization",
    clientRating: 4,
  },
  // Adding more dummy bookings...
  { id: "b11", artistId: "a1", clientId: "c10", eventType: "Theatre Play", eventDate: "2024-07-10", city: "Delhi", duration: 6, amount: 10000, status: "PENDING", clientName: "Prithvi Theatres" },
  { id: "b12", artistId: "a2", clientId: "c11", eventType: "Corporate GIG", eventDate: "2024-09-01", city: "Bangalore", duration: 2, amount: 35000, status: "CONFIRMED", clientName: "Infosys" },
  { id: "b13", artistId: "a3", clientId: "c12", eventType: "Ad Film Direction", eventDate: "2024-05-15", city: "Kolkata", duration: 16, amount: 80000, status: "CONFIRMED", clientName: "Ogilvy" },
  { id: "b14", artistId: "a4", clientId: "c13", eventType: "School Workshop", eventDate: "2024-03-12", city: "Hyderabad", duration: 4, amount: 12000, status: "COMPLETED", clientName: "Oakridge School", clientRating: 5 },
  { id: "b15", artistId: "a6", clientId: "c14", eventType: "VFX Project", eventDate: "2024-04-20", city: "Remote", duration: 40, amount: 60000, status: "PENDING", clientName: "Red Chillies VFX" },
  { id: "b16", artistId: "a8", clientId: "c15", eventType: "Casting Call", eventDate: "2024-05-10", city: "Lucknow", duration: 8, amount: 25000, status: "CONFIRMED", clientName: "Amazon Prime Series" },
  { id: "b17", artistId: "a9", clientId: "c16", eventType: "College Fest", eventDate: "2024-02-14", city: "Jaipur", duration: 1, amount: 20000, status: "COMPLETED", clientName: "BITS Pilani", clientRating: 4 },
  { id: "b18", artistId: "a12", clientId: "c17", eventType: "Line Production", eventDate: "2024-10-10", city: "Goa", duration: 120, amount: 300000, status: "CONFIRMED", clientName: "Dharma Productions" },
  { id: "b19", artistId: "a15", clientId: "c18", eventType: "Set Design", eventDate: "2024-06-15", city: "Chennai", duration: 48, amount: 150000, status: "PENDING", clientName: "Lyca Productions" },
  { id: "b20", artistId: "a21", clientId: "c19", eventType: "Brand Endorsement", eventDate: "2024-05-01", city: "Mumbai", duration: 6, amount: 500000, status: "CANCELLED", clientName: "Nykaa" }
];
