import { FacultyRequirement } from "@/types";

export const facultyRequirements: FacultyRequirement[] = [
  {
    id: "fr1",
    schoolId: "s1",
    schoolName: "National School of Drama (NSD)",
    roleNeeded: "Acting Coach",
    subject: "Method Acting",
    duration: "Long-term",
    budgetMin: 50000,
    budgetMax: 100000,
    city: "Delhi",
    description: "Looking for an experienced method acting coach to handle the first-year diploma students.",
    postedDate: "2024-03-01T10:00:00Z",
    isActive: true
  },
  {
    id: "fr2",
    schoolId: "s2",
    schoolName: "Film and Television Institute of India (FTII)",
    roleNeeded: "Guest Lecturer",
    subject: "Sound Recording & Design",
    duration: "Short-term",
    budgetMin: 20000,
    budgetMax: 50000,
    city: "Pune",
    description: "Two-week intensive workshop on advanced foley and sync sound recording.",
    postedDate: "2024-03-05T14:30:00Z",
    isActive: true
  },
  {
    id: "fr3",
    schoolId: "s3",
    schoolName: "Whistling Woods International",
    roleNeeded: "VFX Instructor",
    subject: "Compositing & CGI",
    duration: "Long-term",
    budgetMin: 80000,
    budgetMax: 150000,
    city: "Mumbai",
    description: "Full-time faculty needed for advanced Nuke and After Effects courses.",
    postedDate: "2024-02-28T09:15:00Z",
    isActive: true
  },
  {
    id: "fr4",
    schoolId: "s4",
    schoolName: "KM Music Conservatory",
    roleNeeded: "Vocal Trainer",
    subject: "Western Classical Vocals",
    duration: "Project-based",
    budgetMin: 30000,
    budgetMax: 60000,
    city: "Chennai",
    description: "Seeking a soprano/tenor for a 3-month special masterclass series.",
    postedDate: "2024-03-10T11:00:00Z",
    isActive: true
  },
  {
    id: "fr5",
    schoolId: "s5",
    schoolName: "Shiamak Davar Institute",
    roleNeeded: "Choreographer",
    subject: "Contemporary Dance",
    duration: "Long-term",
    budgetMin: 40000,
    budgetMax: 80000,
    city: "Mumbai",
    description: "Full-time contemporary instructor required for the intensive training program.",
    postedDate: "2024-03-12T16:45:00Z",
    isActive: true
  },
  {
    id: "fr6",
    schoolId: "s6",
    schoolName: "SRFTI",
    roleNeeded: "Cinematography Mentor",
    subject: "Digital Cinematography",
    duration: "Short-term",
    budgetMin: 25000,
    budgetMax: 55000,
    city: "Kolkata",
    description: "Weekend workshop on RED camera operations and lighting setups.",
    postedDate: "2024-03-15T08:30:00Z",
    isActive: true
  },
  {
    id: "fr7",
    schoolId: "s7",
    schoolName: "Barry John Acting Studio",
    roleNeeded: "Improv Coach",
    subject: "Improvisational Comedy",
    duration: "Project-based",
    budgetMin: 15000,
    budgetMax: 35000,
    city: "Mumbai",
    description: "Looking for an improv expert to run a 4-weekend bootcamp.",
    postedDate: "2024-03-18T12:20:00Z",
    isActive: true
  },
  {
    id: "fr8",
    schoolId: "s8",
    schoolName: "The True School of Music",
    roleNeeded: "DJ Instructor",
    subject: "Electronic Music Production & DJing",
    duration: "Long-term",
    budgetMin: 60000,
    budgetMax: 120000,
    city: "Mumbai",
    description: "Seeking an active club DJ to teach the art of live mixing and track selection.",
    postedDate: "2024-02-20T10:00:00Z",
    isActive: false
  },
  {
    id: "fr9",
    schoolId: "s9",
    schoolName: "Annapurna International School",
    roleNeeded: "Screenwriting Faculty",
    subject: "Script Development",
    duration: "Long-term",
    budgetMin: 70000,
    budgetMax: 110000,
    city: "Hyderabad",
    description: "Full-time faculty to guide students through feature film script development.",
    postedDate: "2024-03-02T13:40:00Z",
    isActive: true
  },
  {
    id: "fr10",
    schoolId: "s10",
    schoolName: "Terence Lewis Professional Training Institute",
    roleNeeded: "Ballet Instructor",
    subject: "Classical Ballet",
    duration: "Short-term",
    budgetMin: 40000,
    budgetMax: 60000,
    city: "Mumbai",
    description: "Guest faculty needed for a 1-month intensive ballet course.",
    postedDate: "2024-03-14T15:10:00Z",
    isActive: true
  },
  {
    id: "fr11",
    schoolId: "s1",
    schoolName: "National School of Drama (NSD)",
    roleNeeded: "Voice Coach",
    subject: "Voice Modulation & Diction",
    duration: "Long-term",
    budgetMin: 45000,
    budgetMax: 85000,
    city: "Delhi",
    description: "Expert needed for classical voice training and Hindi/Urdu diction.",
    postedDate: "2024-03-16T09:00:00Z",
    isActive: true
  },
  {
    id: "fr12",
    schoolId: "s2",
    schoolName: "Film and Television Institute of India (FTII)",
    roleNeeded: "Editor",
    subject: "Non-linear Editing",
    duration: "Project-based",
    budgetMin: 30000,
    budgetMax: 70000,
    city: "Pune",
    description: "Guidance for final year students on their diploma films.",
    postedDate: "2024-03-17T11:30:00Z",
    isActive: true
  },
  {
    id: "fr13",
    schoolId: "s3",
    schoolName: "Whistling Woods International",
    roleNeeded: "Media Management Faculty",
    subject: "Entertainment Business",
    duration: "Long-term",
    budgetMin: 90000,
    budgetMax: 160000,
    city: "Mumbai",
    description: "Seeking industry professional to teach media economics and distribution.",
    postedDate: "2024-03-08T14:00:00Z",
    isActive: true
  },
  {
    id: "fr14",
    schoolId: "s4",
    schoolName: "KM Music Conservatory",
    roleNeeded: "Audio Engineer",
    subject: "Studio Mixing",
    duration: "Short-term",
    budgetMin: 25000,
    budgetMax: 45000,
    city: "Chennai",
    description: "Workshop on analog console mixing and mastering techniques.",
    postedDate: "2024-03-19T10:15:00Z",
    isActive: true
  },
  {
    id: "fr15",
    schoolId: "s5",
    schoolName: "Shiamak Davar Institute",
    roleNeeded: "Fitness Trainer",
    subject: "Dancer Conditioning",
    duration: "Project-based",
    budgetMin: 20000,
    budgetMax: 40000,
    city: "Mumbai",
    description: "Requires a fitness expert to design a conditioning program for dancers.",
    postedDate: "2024-03-20T12:00:00Z",
    isActive: true
  }
];
