import { ProductionHouse } from "@/types";

export const productionHouses: ProductionHouse[] = [
  {
    id: "p1",
    name: "Dharma Productions",
    logo: "https://picsum.photos/seed/dharma/200/200",
    city: "Mumbai",
    type: "Film",
    activeProjects: 4,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
  },
  {
    id: "p2",
    name: "Yash Raj Films",
    logo: "https://picsum.photos/seed/yrf/200/200",
    city: "Mumbai",
    type: "Film",
    activeProjects: 6,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
  },
  {
    id: "p3",
    name: "Red Chillies Entertainment",
    logo: "https://picsum.photos/seed/redchillies/200/200",
    city: "Mumbai",
    type: "Film/OTT",
    activeProjects: 3,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
  },
  {
    id: "p4",
    name: "Phantom Films",
    logo: "https://picsum.photos/seed/phantom/200/200",
    city: "Mumbai",
    type: "Film",
    activeProjects: 2,
    subscriptionStatus: "EXPIRED",
    isVerified: true,
  },
  {
    id: "p5",
    name: "Excel Entertainment",
    logo: "https://picsum.photos/seed/excel/200/200",
    city: "Mumbai",
    type: "Film/OTT",
    activeProjects: 5,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
  },
  {
    id: "p6",
    name: "Balaji Telefilms",
    logo: "https://picsum.photos/seed/balaji/200/200",
    city: "Mumbai",
    type: "TV/OTT",
    activeProjects: 12,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
  },
  {
    id: "p7",
    name: "Maddock Films",
    logo: "https://picsum.photos/seed/maddock/200/200",
    city: "Mumbai",
    type: "Film",
    activeProjects: 3,
    subscriptionStatus: "ACTIVE",
    isVerified: false,
  },
  {
    id: "p8",
    name: "Nadiadwala Grandson Entertainment",
    logo: "https://picsum.photos/seed/nadiadwala/200/200",
    city: "Mumbai",
    type: "Film",
    activeProjects: 2,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
  }
];
