import { School } from "@/types";

export const schools: School[] = [
  {
    id: "s1",
    name: "National School of Drama (NSD)",
    logo: "https://picsum.photos/seed/nsd/200/200",
    city: "Delhi",
    type: "Theatre",
    coursesOffered: ["Acting", "Stage Design", "Direction", "Theatre Techniques"],
    facultyCount: 25,
    studentsEnrolled: 150,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "info@nsd.example.com",
  },
  {
    id: "s2",
    name: "Film and Television Institute of India (FTII)",
    logo: "https://picsum.photos/seed/ftii/200/200",
    city: "Pune",
    type: "Film",
    coursesOffered: ["Direction", "Cinematography", "Sound Recording", "Editing"],
    facultyCount: 40,
    studentsEnrolled: 300,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "admin@ftii.example.com",
  },
  {
    id: "s3",
    name: "Whistling Woods International",
    logo: "https://picsum.photos/seed/wwi/200/200",
    city: "Mumbai",
    type: "Film",
    coursesOffered: ["Filmmaking", "Acting", "Animation", "Media & Communication"],
    facultyCount: 60,
    studentsEnrolled: 500,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "admissions@whistlingwoods.example.com",
  },
  {
    id: "s4",
    name: "KM Music Conservatory",
    logo: "https://picsum.photos/seed/kmmc/200/200",
    city: "Chennai",
    type: "Music",
    coursesOffered: ["Audio Engineering", "Electronic Music Production", "Western Vocals"],
    facultyCount: 20,
    studentsEnrolled: 120,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "info@kmmc.example.com",
  },
  {
    id: "s5",
    name: "Shiamak Davar Institute",
    logo: "https://picsum.photos/seed/shiamak/200/200",
    city: "Mumbai",
    type: "Dance",
    coursesOffered: ["Contemporary", "Bollywood Jazz", "Hip Hop"],
    facultyCount: 30,
    studentsEnrolled: 800,
    subscriptionStatus: "EXPIRED",
    isVerified: true,
    contactEmail: "dance@shiamak.example.com",
  },
  {
    id: "s6",
    name: "Satyajit Ray Film and Television Institute (SRFTI)",
    logo: "https://picsum.photos/seed/srfti/200/200",
    city: "Kolkata",
    type: "Film",
    coursesOffered: ["Direction & Screenplay Writing", "Cinematography", "Editing"],
    facultyCount: 35,
    studentsEnrolled: 250,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "contact@srfti.example.com",
  },
  {
    id: "s7",
    name: "Barry John Acting Studio",
    logo: "https://picsum.photos/seed/barryjohn/200/200",
    city: "Mumbai",
    type: "Theatre",
    coursesOffered: ["Diploma in Film Acting", "Certificate in Acting", "Weekend Acting Program"],
    facultyCount: 15,
    studentsEnrolled: 200,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "bjas@example.com",
  },
  {
    id: "s8",
    name: "The True School of Music",
    logo: "https://picsum.photos/seed/trueschool/200/200",
    city: "Mumbai",
    type: "Music",
    coursesOffered: ["Music Production", "Sound Engineering", "DJing", "Pro Vocals"],
    facultyCount: 25,
    studentsEnrolled: 300,
    subscriptionStatus: "ACTIVE",
    isVerified: false,
    contactEmail: "learn@trueschool.example.com",
  },
  {
    id: "s9",
    name: "Annapurna International School of Film + Media",
    logo: "https://picsum.photos/seed/aisfm/200/200",
    city: "Hyderabad",
    type: "Film",
    coursesOffered: ["Bachelors in Film & Media", "Masters in Film & Media", "Short Courses"],
    facultyCount: 45,
    studentsEnrolled: 400,
    subscriptionStatus: "ACTIVE",
    isVerified: true,
    contactEmail: "info@aisfm.example.com",
  },
  {
    id: "s10",
    name: "Terence Lewis Professional Training Institute",
    logo: "https://picsum.photos/seed/terence/200/200",
    city: "Mumbai",
    type: "Dance",
    coursesOffered: ["Diploma in Dance", "Intensive Training Program", "Open Classes"],
    facultyCount: 20,
    studentsEnrolled: 500,
    subscriptionStatus: "EXPIRED",
    isVerified: true,
    contactEmail: "tlpti@example.com",
  }
];
